---
title: 'Estimating the determinants of cycling: from area to road network levels'
author:
  - name: Robin Lovelace
    email: r.lovelace@leeds.ac.uk
    affiliation: University of Leeds
    corresponding: r.lovelace@leeds.ac.uk
  - name: Malcolm Morgan
    affiliation: University of Leeds
  - name: John Parkin
    affiliation: University of the West of England
address:
  - code: University of Leeds
    address: Institute for Transport Studies (ITS), 34-40 University Road, University of Leeds, Leeds LS2 9JT, United Kingdom 
  - code: Another University
    address: Centre for Transport and Society, University of the West of England, Frenchay Campus, Coldharbour Lane, Bristol, BS16 1QY
abstract: |
  Background: It is important to model the determinants of mode choice for many health-related reasons: to find-out what is holding people back from healthy active travel choices, to understand the drivers of detrimental car dependency, and to identify the causal factors over which public authorities have some control. Another motivation is that model results could feed-into forecasts of behaviour change following specific interventions. Numerous papers have explored the issue but few have been able to provide results that can feed-into models forecasting uptake following local interventions for a number of reasons including small sample size, lack of a temporal component, and use of explanatory variables that cannot easily be applied beyond the case study region. This gap in the literature was identified and tackled as part of a UK Department for Transport funded project to develop a Cycling Infrastructure Prioritisation Toolkit (CyIPT). 
  
  Methods: Origin-destination (OD) data on commuter mode choice was obtained from the 2001 and 2011 Census. The data was processed to ensure that the 2001 data, which was provided at a different geographic level, as compatible with the 2011 data. It was further processed to create a dependent variable (cycling uptake) and explanatory variables including environmental (e.g. length of off-road cycle infrastructure) and demographic (e.g. age and gender splits) factors, for each desire-line. A model was developed to explain cycling uptake as a function of the explanatory variables and forecast future uptake following simulated interventions.
  
  Results: Preliminary results show a clear infrastructure signal in the noise surrounding mode choice but other factors seem to be at play. Further research over the coming months will seek to improve the model and our resulting ability to forecast uptake at the local level from specific interventions.
  
  Conclusions: Newly available data, combined with emerging high performance and open source statistical software, mean that large natural experiments on the impact of new infrastructure on mode choice can now be performed at the national level using geographically detailed data at the origin-destination level. This has the potential to make the prioritisation of new infrastructure much more evidence-based and holds the promise of allowing a-priori benefit-cost estimates to be automated to support transport planners to enable a rapid transition away from fossil fuels and towards healthy travel patterns across the world, in urban and rural areas alike.

bibliography: /home/robin/allrefs.bib
output:
  rticles::elsevier_article:
        number_sections: yes
---

# Preliminary info {-}

- Target journal: transport and health: 
- "3000–6000 words"

# Introduction

- Policy context and need

- The fact it builds on the PCT [@lovelace_propensity_2017]

- Natural experiments with before/after [@heinen_changes_2015] [@prins_causal_2016]
    
- Impact on safety: [@reynolds_impact_2009]

- Categorisations of research into cycling/infrastructure relationship. Target group / trip type (commuting) / dependent variable / geographic level (person, area, school - suggested) - table



## Area-level studies

[@parkin_estimation_2008]

## Organisational level studies

## Route level studies

In route level studies the main variable is at the route level.
Typically these studies involve a single new cycle path being constructed and the resulting change in behaviour being observed.
There is very strong evidence that *existing* cyclists respond to new routes [@heesch_evaluation_2016].

## Individual-level studies

- [@heinen_does_2017; @heinen_role_2011]
    

# Data and methods

# Computation

The method described in the previous section was implemented in the statistical programming language R [@rcoreteam_language_2017].

- Description of the historic uptake script
- Rerunning with different parameters for sensitivity tests

# Results

# Conclusions

# References {#references .unnumbered}
